# Read the documentation: https://symfony.com/bundles/StofDoctrineExtensionsBundle/current/index.html
# See the official DoctrineExtensions documentation for more details: https://github.com/doctrine-extensions/DoctrineExtensions/tree/main/doc
stof_doctrine_extensions:
    default_locale: '%app.default_locale%'
